[[shapes]]
camel_name = "Cube"
snake_name = "cube"
faces = [
    { points = [
        [
            100,
            100,
            100,
        ],
        [
            -100,
            100,
            100,
        ],
        [
            -100,
            -100,
            100,
        ],
        [
            100,
            -100,
            100,
        ],
    ] },
    { points = [
        [
            100,
            100,
            -100,
        ],
        [
            -100,
            100,
            -100,
        ],
        [
            -100,
            -100,
            -100,
        ],
        [
            100,
            -100,
            -100,
        ],
    ] },
    { points = [
        [
            100,
            100,
            100,
        ],
        [
            100,
            -100,
            100,
        ],
        [
            100,
            -100,
            -100,
        ],
        [
            100,
            100,
            -100,
        ],
    ] },
    { points = [
        [
            -100,
            100,
            100,
        ],
        [
            -100,
            -100,
            100,
        ],
        [
            -100,
            -100,
            -100,
        ],
        [
            -100,
            100,
            -100,
        ],
    ] },
    { points = [
        [
            100,
            100,
            100,
        ],
        [
            -100,
            100,
            100,
        ],
        [
            -100,
            100,
            -100,
        ],
        [
            100,
            100,
            -100,
        ],
    ] },
    { points = [
        [
            100,
            -100,
            100,
        ],
        [
            -100,
            -100,
            100,
        ],
        [
            -100,
            -100,
            -100,
        ],
        [
            100,
            -100,
            -100,
        ],
    ] },
]
[[shapes]]
camel_name = "Tetrahedron"
snake_name = "tetrahedron"
faces = [

    { points = [
        [
            100,
            100,
            100,
        ],
        [
            -100,
            -100,
            100,
        ],
        [
            -100,
            100,
            -100,
        ],
    ] },
    { points = [
        [
            100,
            100,
            100,
        ],
        [
            -100,
            100,
            -100,
        ],
        [
            100,
            -100,
            -100,
        ],
    ] },
    { points = [
        [
            -100,
            100,
            -100,
        ],
        [
            100,
            -100,
            -100,
        ],
        [
            100,
            100,
            100,
        ],
    ] },
    { points = [
        [
            -100,
            100,
            -100,
        ],
        [
            100,
            -100,
            -100,
        ],
        [
            -100,
            -100,
            100,
        ],
    ] },
]
