[[shapes]]
name = "cube"
faces = [
    { points = [
        [
            100,
            100,
            100,
        ],
        [
            -100,
            100,
            100,
        ],
        [
            -100,
            -100,
            100,
        ],
        [
            100,
            -100,
            100,
        ],
    ] },
    { points = [
        [
            100,
            100,
            -100,
        ],
        [
            -100,
            100,
            -100,
        ],
        [
            -100,
            -100,
            -100,
        ],
        [
            100,
            -100,
            -100,
        ],
    ] },
    { points = [
        [
            100,
            100,
            100,
        ],
        [
            100,
            -100,
            100,
        ],
        [
            100,
            -100,
            -100,
        ],
        [
            100,
            100,
            -100,
        ],
    ] },
    { points = [
        [
            -100,
            100,
            100,
        ],
        [
            -100,
            -100,
            100,
        ],
        [
            -100,
            -100,
            -100,
        ],
        [
            -100,
            100,
            -100,
        ],
    ] },
    { points = [
        [
            100,
            100,
            100,
        ],
        [
            -100,
            100,
            100,
        ],
        [
            -100,
            100,
            -100,
        ],
        [
            100,
            100,
            -100,
        ],
    ] },
    { points = [
        [
            100,
            -100,
            100,
        ],
        [
            -100,
            -100,
            100,
        ],
        [
            -100,
            -100,
            -100,
        ],
        [
            100,
            -100,
            -100,
        ],
    ] },
]
[[shapes]]
name = "tetrahedron"
faces = [

    { points = [
        [
            100,
            100,
            100,
        ],
        [
            -100,
            -100,
            100,
        ],
        [
            -100,
            100,
            -100,
        ],
    ] },
    { points = [
        [
            100,
            100,
            100,
        ],
        [
            -100,
            100,
            -100,
        ],
        [
            100,
            -100,
            -100,
        ],
    ] },
    { points = [
        [
            -100,
            100,
            -100,
        ],
        [
            100,
            -100,
            -100,
        ],
        [
            100,
            100,
            100,
        ],
    ] },
    { points = [
        [
            -100,
            100,
            -100,
        ],
        [
            100,
            -100,
            -100,
        ],
        [
            -100,
            -100,
            100,
        ],
    ] },
]
